export const referenceTokens = {
  cocoa: "#261e18",
  gold: "#c8912f",
  goldStrong: "#a86e1f",
  canvas: "#eceae4",
  workSurface: "#f4f0e9",
  header: "#fbf8f3",
  card: "#ffffff",
  line: "#e7dfd3",
  lineStrong: "#e0d7c8",
  lineSubtle: "#f3ede2",
  tableHead: "#faf7f1",
  goldSoft: "#efe7d7",
  goldWash: "#fdf8ec",
  text: "#261e18",
  textSecondary: "#4a4136",
  muted: "#8a7f73",
  textSubtle: "#b3a794",
  sidebarInactive: "#c9bcab",
  sidebarMuted: "#8a7c6b",
  sidebarMutedSoft: "#a89a88",
  success: "#3f7d4e",
  warning: "#c05621",
  danger: "#d9524a",
  notice: "#d95d39",
  info: "#3563a8",
  comparison: "#d9cfc0"
} as const;

export const referenceComponentClasses = [
  "ref-shell",
  "ref-page-header",
  "ref-card",
  "ref-table-head",
  "ref-table-row",
  "ref-filter-control",
  "ref-primary-action",
  "ref-secondary-action",
  "ref-status-tag",
  "ref-metric-card"
] as const;
